<Project Sdk="Microsoft.NET.Sdk">

 

  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>

 

  <ItemGroup>
    <Compile Remove="Migrations\20210203191326_added_companyUserIdTO_InuranceuserProfielTable.cs" />
    <Compile Remove="Migrations\20210203191326_added_companyUserIdTO_InuranceuserProfielTable.Designer.cs" />
    <Compile Remove="Migrations\20210205102100_First_Localdb.cs" />
    <Compile Remove="Migrations\20210205102100_First_Localdb.Designer.cs" />
    <Compile Remove="Migrations\20210210154403_modified_insuranceuserProfile_table.cs" />
    <Compile Remove="Migrations\20210210154403_modified_insuranceuserProfile_table.Designer.cs" />
    <Compile Remove="Migrations\20210309202538_Modify_schedulePAyment_table.cs" />
    <Compile Remove="Migrations\20210309202538_Modify_schedulePAyment_table.Designer.cs" />
    <Compile Remove="Migrations\20210309203211_Modify_schedulePAyment_table.cs" />
    <Compile Remove="Migrations\20210309203211_Modify_schedulePAyment_table.Designer.cs" />
    <Compile Remove="Migrations\20210312104636_scac.cs" />
    <Compile Remove="Migrations\20210312104636_scac.Designer.cs" />
    <Compile Remove="Migrations\20210812084429_create-family-tables2.cs" />
    <Compile Remove="Migrations\20210812084429_create-family-tables2.Designer.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.1.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="3.0.0" />
  </ItemGroup>

</Project>
