//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SterlingOTP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SterlingOTP.OTPCentralServiceSoap")]
    public interface OTPCentralServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<SterlingOTP.CreateUserResponse> CreateUserAsync(SterlingOTP.CreateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AssignToken", ReplyAction="*")]
        System.Threading.Tasks.Task<SterlingOTP.AssignTokenResponse> AssignTokenAsync(SterlingOTP.AssignTokenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OtpValidation", ReplyAction="*")]
        System.Threading.Tasks.Task<SterlingOTP.OtpValidationResponse> OtpValidationAsync(SterlingOTP.OtpValidationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MobileUserCreation", ReplyAction="*")]
        System.Threading.Tasks.Task<SterlingOTP.MobileUserCreationResponse> MobileUserCreationAsync(SterlingOTP.MobileUserCreationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActiveMobileToken", ReplyAction="*")]
        System.Threading.Tasks.Task<SterlingOTP.ActiveMobileTokenResponse> ActiveMobileTokenAsync(SterlingOTP.ActiveMobileTokenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUser", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.CreateUserRequestBody Body;
        
        public CreateUserRequest()
        {
        }
        
        public CreateUserRequest(SterlingOTP.CreateUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hashkey;
        
        public CreateUserRequestBody()
        {
        }
        
        public CreateUserRequestBody(string username, string firstname, string lastname, string hashkey)
        {
            this.username = username;
            this.firstname = firstname;
            this.lastname = lastname;
            this.hashkey = hashkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.CreateUserResponseBody Body;
        
        public CreateUserResponse()
        {
        }
        
        public CreateUserResponse(SterlingOTP.CreateUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateUserResult;
        
        public CreateUserResponseBody()
        {
        }
        
        public CreateUserResponseBody(string CreateUserResult)
        {
            this.CreateUserResult = CreateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignToken", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.AssignTokenRequestBody Body;
        
        public AssignTokenRequest()
        {
        }
        
        public AssignTokenRequest(SterlingOTP.AssignTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssignTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string serialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hashkey;
        
        public AssignTokenRequestBody()
        {
        }
        
        public AssignTokenRequestBody(string serialNumber, string username, string hashkey)
        {
            this.serialNumber = serialNumber;
            this.username = username;
            this.hashkey = hashkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.AssignTokenResponseBody Body;
        
        public AssignTokenResponse()
        {
        }
        
        public AssignTokenResponse(SterlingOTP.AssignTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssignTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AssignTokenResult;
        
        public AssignTokenResponseBody()
        {
        }
        
        public AssignTokenResponseBody(string AssignTokenResult)
        {
            this.AssignTokenResult = AssignTokenResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtpValidationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtpValidation", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.OtpValidationRequestBody Body;
        
        public OtpValidationRequest()
        {
        }
        
        public OtpValidationRequest(SterlingOTP.OtpValidationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtpValidationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string otp;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string hashkey;
        
        public OtpValidationRequestBody()
        {
        }
        
        public OtpValidationRequestBody(string otp, string username, string hashkey)
        {
            this.otp = otp;
            this.username = username;
            this.hashkey = hashkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OtpValidationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="OtpValidationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.OtpValidationResponseBody Body;
        
        public OtpValidationResponse()
        {
        }
        
        public OtpValidationResponse(SterlingOTP.OtpValidationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class OtpValidationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OtpValidationResult;
        
        public OtpValidationResponseBody()
        {
        }
        
        public OtpValidationResponseBody(string OtpValidationResult)
        {
            this.OtpValidationResult = OtpValidationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MobileUserCreationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MobileUserCreation", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.MobileUserCreationRequestBody Body;
        
        public MobileUserCreationRequest()
        {
        }
        
        public MobileUserCreationRequest(SterlingOTP.MobileUserCreationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MobileUserCreationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string hashkey;
        
        public MobileUserCreationRequestBody()
        {
        }
        
        public MobileUserCreationRequestBody(string username, string firstname, string lastname, string hashkey)
        {
            this.username = username;
            this.firstname = firstname;
            this.lastname = lastname;
            this.hashkey = hashkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MobileUserCreationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MobileUserCreationResponse", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.MobileUserCreationResponseBody Body;
        
        public MobileUserCreationResponse()
        {
        }
        
        public MobileUserCreationResponse(SterlingOTP.MobileUserCreationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MobileUserCreationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MobileUserCreationResult;
        
        public MobileUserCreationResponseBody()
        {
        }
        
        public MobileUserCreationResponseBody(string MobileUserCreationResult)
        {
            this.MobileUserCreationResult = MobileUserCreationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveMobileTokenRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActiveMobileToken", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.ActiveMobileTokenRequestBody Body;
        
        public ActiveMobileTokenRequest()
        {
        }
        
        public ActiveMobileTokenRequest(SterlingOTP.ActiveMobileTokenRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActiveMobileTokenRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SerialNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string hashkey;
        
        public ActiveMobileTokenRequestBody()
        {
        }
        
        public ActiveMobileTokenRequestBody(string SerialNumber, string hashkey)
        {
            this.SerialNumber = SerialNumber;
            this.hashkey = hashkey;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActiveMobileTokenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActiveMobileTokenResponse", Namespace="http://tempuri.org/", Order=0)]
        public SterlingOTP.ActiveMobileTokenResponseBody Body;
        
        public ActiveMobileTokenResponse()
        {
        }
        
        public ActiveMobileTokenResponse(SterlingOTP.ActiveMobileTokenResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActiveMobileTokenResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ActiveMobileTokenResult;
        
        public ActiveMobileTokenResponseBody()
        {
        }
        
        public ActiveMobileTokenResponseBody(string ActiveMobileTokenResult)
        {
            this.ActiveMobileTokenResult = ActiveMobileTokenResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface OTPCentralServiceSoapChannel : SterlingOTP.OTPCentralServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class OTPCentralServiceSoapClient : System.ServiceModel.ClientBase<SterlingOTP.OTPCentralServiceSoap>, SterlingOTP.OTPCentralServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public OTPCentralServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(OTPCentralServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), OTPCentralServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTPCentralServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(OTPCentralServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTPCentralServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(OTPCentralServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public OTPCentralServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SterlingOTP.CreateUserResponse> SterlingOTP.OTPCentralServiceSoap.CreateUserAsync(SterlingOTP.CreateUserRequest request)
        {
            return base.Channel.CreateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<SterlingOTP.CreateUserResponse> CreateUserAsync(string username, string firstname, string lastname, string hashkey)
        {
            SterlingOTP.CreateUserRequest inValue = new SterlingOTP.CreateUserRequest();
            inValue.Body = new SterlingOTP.CreateUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.hashkey = hashkey;
            return ((SterlingOTP.OTPCentralServiceSoap)(this)).CreateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SterlingOTP.AssignTokenResponse> SterlingOTP.OTPCentralServiceSoap.AssignTokenAsync(SterlingOTP.AssignTokenRequest request)
        {
            return base.Channel.AssignTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SterlingOTP.AssignTokenResponse> AssignTokenAsync(string serialNumber, string username, string hashkey)
        {
            SterlingOTP.AssignTokenRequest inValue = new SterlingOTP.AssignTokenRequest();
            inValue.Body = new SterlingOTP.AssignTokenRequestBody();
            inValue.Body.serialNumber = serialNumber;
            inValue.Body.username = username;
            inValue.Body.hashkey = hashkey;
            return ((SterlingOTP.OTPCentralServiceSoap)(this)).AssignTokenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SterlingOTP.OtpValidationResponse> SterlingOTP.OTPCentralServiceSoap.OtpValidationAsync(SterlingOTP.OtpValidationRequest request)
        {
            return base.Channel.OtpValidationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SterlingOTP.OtpValidationResponse> OtpValidationAsync(string otp, string username, string hashkey)
        {
            SterlingOTP.OtpValidationRequest inValue = new SterlingOTP.OtpValidationRequest();
            inValue.Body = new SterlingOTP.OtpValidationRequestBody();
            inValue.Body.otp = otp;
            inValue.Body.username = username;
            inValue.Body.hashkey = hashkey;
            return ((SterlingOTP.OTPCentralServiceSoap)(this)).OtpValidationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SterlingOTP.MobileUserCreationResponse> SterlingOTP.OTPCentralServiceSoap.MobileUserCreationAsync(SterlingOTP.MobileUserCreationRequest request)
        {
            return base.Channel.MobileUserCreationAsync(request);
        }
        
        public System.Threading.Tasks.Task<SterlingOTP.MobileUserCreationResponse> MobileUserCreationAsync(string username, string firstname, string lastname, string hashkey)
        {
            SterlingOTP.MobileUserCreationRequest inValue = new SterlingOTP.MobileUserCreationRequest();
            inValue.Body = new SterlingOTP.MobileUserCreationRequestBody();
            inValue.Body.username = username;
            inValue.Body.firstname = firstname;
            inValue.Body.lastname = lastname;
            inValue.Body.hashkey = hashkey;
            return ((SterlingOTP.OTPCentralServiceSoap)(this)).MobileUserCreationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SterlingOTP.ActiveMobileTokenResponse> SterlingOTP.OTPCentralServiceSoap.ActiveMobileTokenAsync(SterlingOTP.ActiveMobileTokenRequest request)
        {
            return base.Channel.ActiveMobileTokenAsync(request);
        }
        
        public System.Threading.Tasks.Task<SterlingOTP.ActiveMobileTokenResponse> ActiveMobileTokenAsync(string SerialNumber, string hashkey)
        {
            SterlingOTP.ActiveMobileTokenRequest inValue = new SterlingOTP.ActiveMobileTokenRequest();
            inValue.Body = new SterlingOTP.ActiveMobileTokenRequestBody();
            inValue.Body.SerialNumber = SerialNumber;
            inValue.Body.hashkey = hashkey;
            return ((SterlingOTP.OTPCentralServiceSoap)(this)).ActiveMobileTokenAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OTPCentralServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.OTPCentralServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.OTPCentralServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://az-cpibap2-serv/OTPCentralService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.OTPCentralServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://az-cpibap2-serv/OTPCentralService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            OTPCentralServiceSoap,
            
            OTPCentralServiceSoap12,
        }
    }
}
